/**
 * Stripe client backstop (2026-08-01, Connect Your Stripe item 4).
 * Mirrors lib/generation/supabase-scaffold.ts exactly: fills a gap
 * deterministically, never touches model-emitted content. When a
 * project has a real Stripe connection and the model didn't emit (or
 * only partially emitted) `src/lib/stripe.ts`, this injects it with
 * the connection's REAL literal publishable key — never a placeholder.
 * This is the mechanism that makes it safe to tell the model "a
 * stripePromise exists at src/lib/stripe.ts" in the prompt contract
 * (lib/prompts/stripe-block.ts): the file is GUARANTEED to either be
 * the model's own correct version or this exact real one, never absent
 * and never fake.
 *
 * Deliberately case-insensitive on the path check, matching
 * `ensureSupabaseClientFile`'s casing-bug tolerance.
 *
 * EXTENDED same day with `ensureStripeBackendFunction`: when a project
 * has BOTH a Stripe and a Supabase connection, this also injects a
 * real, deployable Supabase Edge Function
 * (supabase/functions/create-payment-intent/index.ts) that creates a
 * PaymentIntent server-side. Unlike src/lib/stripe.ts, this file is
 * pure boilerplate — it never varies by project content — so it is
 * ALWAYS deterministically generated by AIWP, never left to the model,
 * the same "generate real code, never a placeholder" posture as
 * everything else in this file. The file reads its Stripe SECRET key
 * from a Supabase function secret (`Deno.env.get("STRIPE_SECRET_KEY")`)
 * that the USER sets directly with the Supabase CLI — AIWP never
 * collects, sees, or stores it, matching the hard rule in
 * lib/stripe-connect/actions.ts. Deploying it is a manual step the
 * user takes themselves (`supabase functions deploy
 * create-payment-intent`), same generate-but-don't-execute posture as
 * `supabase/schema.sql`.
 */

import type { GeneratedFile } from "@/lib/generation/types";
import type { StripeConnection } from "@/lib/stripe-connect/actions";

const CLIENT_FILE_PATH = "src/lib/stripe.ts";

function clientFileContent(connection: StripeConnection): string {
  return `import { loadStripe } from '@stripe/stripe-js'

// Auto-generated by AI Website Powerhouse from your saved Stripe
// connection. Publishable key only — Stripe documents this key as
// safe to expose client-side. Do not hardcode a different key
// elsewhere in this project — always import { stripePromise } from
// this file.
//
// NOTE: completing a real charge requires a backend endpoint (your
// own server) that creates a PaymentIntent using your Stripe SECRET
// key. This project deliberately never collects or stores a secret
// key, so checkout UI built against this file can validate cards but
// cannot complete a real charge until you add that backend.
export const stripePromise = loadStripe('${connection.publishableKey}')
`;
}

export interface StripeClientBackstopResult {
  files: GeneratedFile[];
  /** True when this pass injected the client file (it was missing). */
  injected: boolean;
}

/**
 * Ensures `src/lib/stripe.ts` exists with the real publishable key
 * whenever a project is connected. No-op (byte-identical) when the
 * project has no connection, the file already exists (any casing), or
 * there are no files at all.
 */
export function ensureStripeClientFile(
  files: GeneratedFile[],
  connection: StripeConnection | null,
): StripeClientBackstopResult {
  if (connection === null || files.length === 0) {
    return { files, injected: false };
  }
  const alreadyPresent = files.some(
    (f) => f.name.toLowerCase() === CLIENT_FILE_PATH.toLowerCase(),
  );
  if (alreadyPresent) {
    return { files, injected: false };
  }
  return {
    files: [
      ...files,
      { name: CLIENT_FILE_PATH, content: clientFileContent(connection) },
    ],
    injected: true,
  };
}

/**
 * Plain-language chat note for when the client file was injected
 * (mirrors `supabaseClientInjectedNote`'s tone). Returns null when
 * nothing was injected.
 */
export function stripeClientInjectedNote(injected: boolean): string | null {
  if (!injected) return null;
  return (
    "Connected your Stripe account: added src/lib/stripe.ts with your " +
    "real publishable key so checkout UI can use it."
  );
}

/**
 * Plain-language reminder for whenever a round's file set actually
 * builds Stripe checkout UI (detected by an "@stripe/react-stripe-js"
 * import outside the client file itself) — the same limitation the
 * prompt block already told the model, surfaced to the user too so
 * nobody is surprised a test submission doesn't charge a real card.
 * Returns null when no file uses the Stripe UI package.
 */
export function stripeCheckoutBuiltNote(files: GeneratedFile[]): string | null {
  const usesStripeUi = files.some(
    (f) =>
      f.name.toLowerCase() !== CLIENT_FILE_PATH.toLowerCase() &&
      f.content.includes("@stripe/react-stripe-js"),
  );
  if (!usesStripeUi) return null;
  return (
    "Built real Stripe checkout UI against your publishable key. " +
    "Completing an actual charge still needs a real PaymentIntent " +
    "created server-side — see the comment in src/lib/stripe.ts for " +
    "what's needed."
  );
}

const BACKEND_FUNCTION_PATH = "supabase/functions/create-payment-intent/index.ts";

function backendFunctionContent(): string {
  return `// Auto-generated by AI Website Powerhouse. Creates a real Stripe
// PaymentIntent server-side — this MUST run on a server, never in the
// browser, because it needs your Stripe SECRET key.
//
// Deploy it:
//   supabase functions deploy create-payment-intent
// Then set your secret key as a function secret (never commit it,
// never paste it into AIWP — AIWP never sees or stores this value):
//   supabase secrets set STRIPE_SECRET_KEY=sk_test_...
//
// SECURITY NOTE: this trusts the "amount" sent by the browser, which
// is fine for local testing but NOT safe for real payments — a user
// could edit the request and pay less than the real price. Before
// accepting real payments, compute the amount yourself here (e.g.
// look up the real price from your own Supabase table by product id)
// instead of trusting whatever the client sends.

import Stripe from "npm:stripe@^22";

const stripeSecretKey = Deno.env.get("STRIPE_SECRET_KEY");

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (stripeSecretKey === undefined) {
    return new Response(
      JSON.stringify({
        error:
          "STRIPE_SECRET_KEY is not set. Run: supabase secrets set STRIPE_SECRET_KEY=sk_test_...",
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      },
    );
  }

  try {
    const { amount, currency } = await req.json();

    if (typeof amount !== "number" || !Number.isInteger(amount) || amount <= 0) {
      return new Response(
        JSON.stringify({
          error:
            "amount must be a positive integer, in the smallest currency unit (e.g. cents).",
        }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        },
      );
    }

    const stripe = new Stripe(stripeSecretKey);
    const paymentIntent = await stripe.paymentIntents.create({
      amount,
      currency: typeof currency === "string" ? currency : "usd",
      automatic_payment_methods: { enabled: true },
    });

    return new Response(
      JSON.stringify({ clientSecret: paymentIntent.client_secret }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (error) {
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : String(error),
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      },
    );
  }
});
`;
}

export interface StripeBackendBackstopResult {
  files: GeneratedFile[];
  /** True when this pass injected the Edge Function (it was missing). */
  injected: boolean;
}

/**
 * Ensures the ready-to-deploy create-payment-intent Edge Function
 * exists whenever a project has BOTH a Stripe connection AND a
 * Supabase connection (it needs a Supabase project to deploy to) AND
 * the project's files actually build Stripe checkout UI (no point
 * scaffolding a backend before there is a frontend to call it — same
 * signal `stripeCheckoutBuiltNote` uses). No-op when disconnected,
 * when there's no Supabase project to deploy to, when no file uses
 * the Stripe UI package yet, or when the function file already exists
 * (any casing) — the user may have customized it (e.g. added real
 * amount-lookup logic per the security note), so it is never
 * overwritten once present.
 */
export function ensureStripeBackendFunction(
  files: GeneratedFile[],
  stripeConnection: StripeConnection | null,
  hasSupabaseConnection: boolean,
): StripeBackendBackstopResult {
  if (stripeConnection === null || !hasSupabaseConnection || files.length === 0) {
    return { files, injected: false };
  }
  const usesStripeUi = files.some((f) =>
    f.content.includes("@stripe/react-stripe-js"),
  );
  if (!usesStripeUi) {
    return { files, injected: false };
  }
  const alreadyPresent = files.some(
    (f) => f.name.toLowerCase() === BACKEND_FUNCTION_PATH.toLowerCase(),
  );
  if (alreadyPresent) {
    return { files, injected: false };
  }
  return {
    files: [
      ...files,
      { name: BACKEND_FUNCTION_PATH, content: backendFunctionContent() },
    ],
    injected: true,
  };
}

/**
 * The exact text of the backend-function note (below), exported as a
 * constant so `lib/generation/blocker-notes.ts` (2026-08-01, Chat/Plan
 * Mode item 1) can recognize it by exact equality instead of a second,
 * driftable copy of the string.
 */
export const STRIPE_BACKEND_FUNCTION_NOTE_TEXT =
  "Added a ready-to-deploy backend at " +
  "supabase/functions/create-payment-intent/index.ts so checkout can " +
  "actually charge a card. Two steps to activate it: run `supabase " +
  "functions deploy create-payment-intent`, then `supabase secrets " +
  "set STRIPE_SECRET_KEY=sk_test_...` with your own secret key " +
  "(AIWP never sees it). Read the security note at the top of the " +
  "file before accepting real payments.";

/**
 * Plain-language chat note for when the Edge Function was injected.
 * Spells out the two manual steps (deploy, set the secret) since
 * neither can happen automatically — AIWP never touches the user's
 * Supabase CLI or their Stripe secret key. Returns null when nothing
 * was injected.
 */
export function stripeBackendFunctionInjectedNote(
  injected: boolean,
): string | null {
  if (!injected) return null;
  return STRIPE_BACKEND_FUNCTION_NOTE_TEXT;
}
