/**
 * Supabase client backstop (2026-07-31, Connect Your Supabase item 4).
 * Design: PLAN/Feature-Connect-Your-Supabase.md §5.
 *
 * Same shape as `ensureLocalImportsResolve` in react-scaffold.ts:
 * fills a gap deterministically, never touches model-emitted content.
 * When a project has a real Supabase connection and the model didn't
 * emit (or only partially emitted) `src/lib/supabase.ts`, this injects
 * it with the connection's REAL literal url/anon key — never a
 * placeholder. This is the mechanism that makes it safe to tell the
 * model "a client exists at src/lib/supabase.ts" in the prompt
 * contract (lib/prompts/supabase-block.ts): the file is GUARANTEED to
 * either be the model's own correct version or this exact real one,
 * never absent and never fake.
 *
 * Deliberately case-insensitive on the path check, matching
 * `ensureLocalImportsResolve`'s casing-bug tolerance — a
 * differently-cased existing file is left alone, not shadowed.
 */

import type { GeneratedFile } from "@/lib/generation/types";
import type { SupabaseConnection } from "@/lib/supabase-connect/actions";

const CLIENT_FILE_PATH = "src/lib/supabase.ts";
const SCHEMA_FILE_PATH = "supabase/schema.sql";

function clientFileContent(connection: SupabaseConnection): string {
  return `import { createClient } from '@supabase/supabase-js'

// Auto-generated by AI Website Powerhouse from your saved Supabase
// connection. Do not hardcode a different URL or key elsewhere in
// this project — always import { supabase } from this file.
export const supabase = createClient(
  '${connection.url}',
  '${connection.anonKey}'
)
`;
}

export interface SupabaseClientBackstopResult {
  files: GeneratedFile[];
  /**
   * True when this pass wrote the client file — either because it was
   * missing (`corrected: false`), or because a model-authored version
   * existed but didn't contain the real connection values
   * (`corrected: true`). False when nothing needed to change.
   */
  injected: boolean;
  /**
   * True specifically when an existing, model-authored
   * `src/lib/supabase.ts` was replaced because it didn't use the real
   * credentials — most commonly a model writing
   * `import.meta.env.VITE_SUPABASE_URL`-style code instead of
   * importing the pre-built client, per the SUPABASE BACKEND
   * CONNECTED prompt instruction (lib/prompts/supabase-block.ts).
   * False when the file was newly added or was already correct.
   */
  corrected: boolean;
}

/**
 * Ensures `src/lib/supabase.ts` exists AND actually contains the real
 * connection values whenever a project is connected.
 *
 * 2026-08-01 fix: the original version only checked that a file
 * existed at this path, on the assumption a model that emitted its
 * own `src/lib/supabase.ts` got it right. In practice a model can
 * satisfy "a file exists here" while still writing
 * `import.meta.env.VITE_SUPABASE_URL` (a pattern it knows from
 * general Vite/Supabase training data) instead of the real literal
 * values. AIWP never ships a `.env` file, so that pattern silently
 * produces `createClient('', '')` at module load — which throws
 * before React ever mounts, i.e. a blank white screen with no visible
 * error and no chat note explaining why. This now verifies the
 * existing file actually contains the real URL and anon key as
 * substrings before trusting it, and replaces it (never appends a
 * duplicate) when it doesn't.
 *
 * No-op (byte-identical) when the project has no connection, there
 * are no files at all, or an existing file already has the real
 * values.
 */
export function ensureSupabaseClientFile(
  files: GeneratedFile[],
  connection: SupabaseConnection | null,
): SupabaseClientBackstopResult {
  if (connection === null || files.length === 0) {
    return { files, injected: false, corrected: false };
  }
  const existingIndex = files.findIndex(
    (f) => f.name.toLowerCase() === CLIENT_FILE_PATH.toLowerCase(),
  );
  if (existingIndex === -1) {
    return {
      files: [
        ...files,
        { name: CLIENT_FILE_PATH, content: clientFileContent(connection) },
      ],
      injected: true,
      corrected: false,
    };
  }
  const existing = files[existingIndex];
  const hasRealCredentials =
    existing.content.includes(connection.url) &&
    existing.content.includes(connection.anonKey);
  if (hasRealCredentials) {
    return { files, injected: false, corrected: false };
  }
  const nextFiles = [...files];
  nextFiles[existingIndex] = {
    name: existing.name,
    content: clientFileContent(connection),
  };
  return { files: nextFiles, injected: true, corrected: true };
}

/**
 * The exact text of the schema-note (below), exported as a constant
 * so `lib/generation/blocker-notes.ts` (2026-08-01, Chat/Plan Mode
 * item 1) can recognize it by exact equality instead of a second,
 * driftable copy of the string. Whenever this changes, the resume
 * button's classifier keeps working automatically — there is only
 * ever one copy of this text in the codebase.
 */
export const SUPABASE_SCHEMA_NOTE_TEXT =
  "New tables needed: run supabase/schema.sql in your Supabase project's " +
  "SQL editor, then ask me to continue — AIWP never runs SQL against " +
  "your project on its own.";

/**
 * Plain-language chat note for when the client file was injected or
 * corrected (2026-07-31, mirrors `localImportStubNote`'s tone; 2026-
 * 08-01 added the corrected case). Returns null when nothing changed
 * — the common case once a project's src/lib/supabase.ts has been
 * emitted once correctly and kept across edits.
 */
export function supabaseClientInjectedNote(
  result: Pick<SupabaseClientBackstopResult, "injected" | "corrected">,
): string | null {
  if (!result.injected) return null;
  if (result.corrected) {
    return (
      "Fixed src/lib/supabase.ts: it existed but wasn't using your real " +
      "Supabase connection (it looked for a .env file, which AIWP " +
      "doesn't generate) — replaced it with your real URL and anon key " +
      "so auth and data actually work instead of showing a blank screen."
    );
  }
  return (
    "Connected your Supabase project: added src/lib/supabase.ts with your " +
    "real connection so the app can read/write real data."
  );
}

/**
 * Plain-language chat note for when the model emitted a
 * supabase/schema.sql file this round — the UX flag from the design
 * doc §4 ("no new step in the generate/chat flow itself... a chat note
 * when a generation emits a schema.sql"). Returns null when no schema
 * file is present in the final file set.
 */
export function supabaseSchemaNote(files: GeneratedFile[]): string | null {
  const hasSchema = files.some(
    (f) => f.name.toLowerCase() === SCHEMA_FILE_PATH.toLowerCase(),
  );
  if (!hasSchema) return null;
  return SUPABASE_SCHEMA_NOTE_TEXT;
}
